### ISSUE TITLE
與原作者的模型不匹配

### ISSUE THREAD

**Issue by tp6wu0ujoy** [ZaVang/GPT-SoVits#12]
想請教一下模型怎麼放才正確，
我路徑是
\pretrained_models\gpt_weights\pretrained\s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt
\pretrained_models\sovits_weights\pretrained\s2D488k.pth
\pretrained_models\sovits_weights\pretrained\s2G488k.pth

不太清楚sovits的G模型和D模型的差異 但原作者都是放G模型 所以我在webui也選pretrained\s2G488k.pth
若選擇s2D488k.pth可以跑成功但出來的音檔沒有聲音

Traceback (most recent call last):
  File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/root/GPT-SoVits/server/webui.py", line 89, in get_tts_wav
    tts_inference.change_sovits_weights(sovits_model)
  File "/root/GPT-SoVits/src/inference/infer_tool.py", line 96, in change_sovits_weights
    self.sovits_model.load_state_dict(model_dict["weight"], strict=False)
  File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2584, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for enc_p.text_embedding.weight: copying a param with shape torch.Size([732, 192]) from checkpoint, the shape in current model is torch.Size([322, 192]).
        size mismatch for ref_enc.spectral.0.fc.weight: copying a param with shape torch.Size([128, 704]) from checkpoint, the shape in current model is torch.Size([128, 1025]).
        
        看起來是模型版本不匹配 請教大佬是用哪個版本的模型 我這個應該是目前最新的

**Comment by ZaVang** [comment]
我这个是v1版本，原作者出了v2版本，我还没来得及更新，他的text文件夹里的symbols，还有config都和第一版本的不一样所以导致模型不匹配。

**Comment by ZaVang** [comment]
> 想請教一下模型怎麼放才正確， 我路徑是 \pretrained_models\gpt_weights\pretrained\s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt \pretrained_models\sovits_weights\pretrained\s2D488k.pth \pretrained_models\sovits_weights\pretrained\s2G488k.pth
> 
> 不太清楚sovits的G模型和D模型的差異 但原作者都是放G模型 所以我在webui也選pretrained\s2G488k.pth 若選擇s2D488k.pth可以跑成功但出來的音檔沒有聲音
> 
> Traceback (most recent call last): File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events response = await route_utils.call_process_api( File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api output = await app.get_blocks().process_api( File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api result = await self.call_function( File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function prediction = await anyio.to_thread.run_sync( # type: ignore File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync return await get_async_backend().run_sync_in_worker_thread( File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread return await future File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1005, in run result = context.run(func, *args) File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper response = f(*args, **kwargs) File "/root/GPT-SoVits/server/webui.py", line 89, in get_tts_wav tts_inference.change_sovits_weights(sovits_model) File "/root/GPT-SoVits/src/inference/infer_tool.py", line 96, in change_sovits_weights self.sovits_model.load_state_dict(model_dict["weight"], strict=False) File "/root/anaconda3/envs/gptapi/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2584, in load_state_dict raise RuntimeError( RuntimeError: Error(s) in loading state_dict for SynthesizerTrn: size mismatch for enc_p.text_embedding.weight: copying a param with shape torch.Size([732, 192]) from checkpoint, the shape in current model is torch.Size([322, 192]). size mismatch for ref_enc.spectral.0.fc.weight: copying a param with shape torch.Size([128, 704]) from checkpoint, the shape in current model is torch.Size([128, 1025]).
> 
> ```
>     看起來是模型版本不匹配 請教大佬是用哪個版本的模型 我這個應該是目前最新的
> ```

我这个是v1版本，原作者出了v2版本，我还没来得及更新，他的text文件夹里的symbols，还有config都和第一版本的不一样所以导致模型不匹配。
