### ISSUE TITLE
api執行問題

### ISSUE THREAD

**Issue by tp6wu0ujoy** [ZaVang/GPT-SoVits#13]
python server/app.py

Traceback (most recent call last):
  File "/root/GPT-SoVits/server/app.py", line 22, in <module>
    from server.asr import audio_line_check
  File "/root/GPT-SoVits/server/asr.py", line 1, in <module>
    from agent_kernel import get_llm_client, ASRRequest
ModuleNotFoundError: No module named 'agent_kernel'

請問這個agent_kernel要去哪裡下載 或是我需要有甚麼前置步驟

**Comment by ZaVang** [comment]
这是个私人项目，注释掉有关的即可

**Comment by ZaVang** [comment]
> python server/app.py
> 
> Traceback (most recent call last): File "/root/GPT-SoVits/server/app.py", line 22, in from server.asr import audio_line_check File "/root/GPT-SoVits/server/asr.py", line 1, in from agent_kernel import get_llm_client, ASRRequest ModuleNotFoundError: No module named 'agent_kernel'
> 
> 請問這個agent_kernel要去哪裡下載 或是我需要有甚麼前置步驟

这是个私人项目，注释掉即可
